# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title mode
#' @description
#'   This function returns the most frequently occuring value in an integer vector (mode).
#'   If there are more than one values satusfying this definition, it returns one of them
#'   (but there is no rule which one).
#'
#' @param x - an integer vector
#' @return - the most frequently occuring value
#'
#' @export
mode <- function(x) {
    .Call('h6_mode', PACKAGE = 'h6', x)
}

#' @title perms
#' @description
#'   This function returns matrix with all permutations of sequence 1,2,...,n
#'   where n is given as input.
#'
#' @param n - number of elements to permute
#' @return - matrix with all permutations of 1,2,...,n sequence
#'
#' @export
perms <- function(n) {
    .Call('h6_perms', PACKAGE = 'h6', n)
}

#' @title simplify2array2
#' @description
#'   This function transforms input list into an array if it is possible.
#'
#' @param x - list
#' @return If input list consists of only numeric vectors of equal length then
#'   the return value is its array version. Otherwise input list is returned.
#'
#' @export
simplify2array2 <- function(x) {
    .Call('h6_simplify2array2', PACKAGE = 'h6', x)
}

